apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/mykhailokhil/demo-api
    newTag: sha-68dd077  # updated automatically by Argo CD Image Updater (platform/image-updater)
patches:
  # kustomize's "replicas:" field doesn't support the Rollout kind, so patch it
  - target:
      kind: Rollout
      name: demo-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: IngressRoute
      name: demo-api
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`demo-dev.localtest.me`)
  - target:
      kind: Certificate
      name: demo-api
    patch: |-
      - op: replace
        path: /spec/dnsNames/0
        value: demo-dev.localtest.me
