apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/mykhailokhil/demo-api
    digest: sha256:b41bd517e5843ef924117786da12404d2683d2c79374d9bb73c67115479b16f3   # dev: bumped by Image Updater (T12); staging/prod: by promotion PR (T13)
replicas:
  - name: demo-api
    count: 2
